create table multi_age_composite_classes_final_2022_unpivot as
select * from
(
UNPIVOT 
(select "School code" as school_code,"School Name" as school_name,
PCT_COMPOSITE_CLASSES_14,
PCT_COMPOSITE_CLASSES_15,
PCT_COMPOSITE_CLASSES_16,
PCT_COMPOSITE_CLASSES_17,
PCT_COMPOSITE_CLASSES_18,
PCT_COMPOSITE_CLASSES_19,
PCT_COMPOSITE_CLASSES_21,
PCT_COMPOSITE_CLASSES_22,
from multi_age_composite_classes_final_2022
)A
ON 
PCT_COMPOSITE_CLASSES_14 as "2014",
PCT_COMPOSITE_CLASSES_15 as "2015",
PCT_COMPOSITE_CLASSES_16 as "2016",
PCT_COMPOSITE_CLASSES_17 as "2017",
PCT_COMPOSITE_CLASSES_18 as "2018",
PCT_COMPOSITE_CLASSES_19 as "2019",
PCT_COMPOSITE_CLASSES_21 as "2021",
PCT_COMPOSITE_CLASSES_22 as "2022"
into
NAME Year
VALUE multi_age_composite_class
)unpivot_tb